# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 10:10
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.CharField(max_length=4)),
                ('address_type', models.CharField(choices=[('PR', 'Permanent'), ('TM', 'Temporary')], default='TM', max_length=2, verbose_name='Address Type')),
                ('address1', models.CharField(max_length=100, verbose_name='Address 1')),
                ('address2', models.CharField(max_length=100, verbose_name='Address 2')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('state', models.CharField(max_length=30, verbose_name='State')),
                ('zipcode', models.CharField(max_length=10, verbose_name='Zip Code')),
                ('is_active', models.BooleanField(verbose_name='Current address is permanent address')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(choices=[('SSC', 'Senior Secondary'), ('HSC', 'Higher Secondary'), ('GRAD', 'Graduate'), ('PG', 'Post Graduate')], max_length=5, verbose_name='Qualification')),
                ('specialization', models.CharField(blank=True, max_length=30, null=True, verbose_name='Specialization')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('institute', models.CharField(max_length=50, verbose_name='Institution')),
                ('overall_marks', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Total Score/GPA')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousEmployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='Company Name')),
                ('employed_from', models.DateField(verbose_name='Start Date')),
                ('employed_upto', models.DateField(verbose_name='End Date')),
                ('pf_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='PF Number')),
                ('last_ctc', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Last CTC')),
                ('reason_for_exit', models.CharField(max_length=50, verbose_name='Reason for Exit')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name='created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('company_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeForms.Address')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan', models.CharField(max_length=10, unique=True, verbose_name='PAN Number')),
                ('aadhar_card', models.CharField(max_length=12, unique=True, verbose_name='Aadhar Card')),
                ('dl', models.CharField(max_length=10, unique=True, verbose_name='Driving License')),
                ('passport', models.CharField(max_length=10, unique=True, verbose_name='Passport')),
                ('voter_id', models.CharField(max_length=10, unique=True, verbose_name='Voter ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=15, verbose_name='Middle Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2, verbose_name='Gender')),
                ('nationality', models.CharField(max_length=30, verbose_name='Nationality')),
                ('marital_status', models.CharField(choices=[('MA', 'Married'), ('WD', 'Windowed'), ('SE', 'Seperated'), ('DV', 'Divorced'), ('SG', 'Single')], max_length=10, verbose_name='Marital Status')),
                ('wedding_date', models.DateField(blank=True, null=True, verbose_name='Wedding Date')),
                ('blood_group', models.CharField(blank=True, choices=[('00', 'A+'), ('01', 'A-'), ('02', 'B+'), ('03', 'B-'), ('04', 'O+'), ('05', 'O-'), ('06', 'AB+'), ('07', 'AB-')], max_length=3, verbose_name='Blood Group')),
                ('mobile_phone', models.CharField(max_length=15, unique=True, verbose_name='Mobile Phone')),
                ('land_phone', models.CharField(blank=True, max_length=15, verbose_name='Landline Number')),
                ('emergency_phone', models.CharField(max_length=15, unique=True, verbose_name='Emergency Contact Number')),
                ('personal_email', models.EmailField(max_length=250, unique=True, verbose_name='Personal E-mail')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeForms.Address')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
