# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-05 05:20
from __future__ import unicode_literals

import EmployeeForms.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('PR', 'Permanent'), ('TM', 'Temporary')], default='PR', max_length=2, verbose_name='Address Type')),
                ('address1', models.CharField(max_length=200, verbose_name='Address 1')),
                ('address2', models.CharField(max_length=200, verbose_name='Address 2')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('state', models.CharField(max_length=30, verbose_name='State')),
                ('zipcode', models.CharField(max_length=10, verbose_name='Zip Code')),
                ('employee', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='ConfirmationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_code', models.CharField(max_length=100, unique=True, verbose_name='Confirmation Code')),
                ('username', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_type', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('DS', 'Distance Education')], default='FT', max_length=5, verbose_name='Education Type')),
                ('qualification', models.CharField(choices=[('SSC', 'Senior Secondary'), ('HSC', 'Higher Secondary'), ('GRAD', 'Graduate'), ('PG', 'Post Graduate'), ('PhD', 'Doctrate'), ('Other', 'Others')], max_length=5, verbose_name='Qualification')),
                ('specialization', models.CharField(blank=True, max_length=30, null=True, verbose_name='Specialization')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('institute', models.CharField(max_length=50, verbose_name='Institution')),
                ('board_university', models.CharField(blank=True, max_length=50, null=True, verbose_name='Board/University')),
                ('overall_marks', models.FloatField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Total Score/GPA')),
                ('marks_card_attachment', models.FileField(blank=True, null=True, upload_to=EmployeeForms.models.content_file_name, verbose_name='Marks card Attachment')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(blank=True, choices=[('MA', 'Married'), ('SG', 'Single'), ('SE', 'Seperated'), ('DV', 'Divorced'), ('WD', 'Windowed')], max_length=10, null=True, verbose_name='Marital Status')),
                ('wedding_date', models.DateField(blank=True, null=True, verbose_name='Wedding Date')),
                ('spouse_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Spouse Name')),
                ('no_of_children', models.CharField(blank=True, max_length=10, null=True, verbose_name='Number of Children')),
                ('mother_name', models.CharField(max_length=30, verbose_name='Mother Name')),
                ('mother_dob', models.DateField(blank=True, null=True, verbose_name='Mother Date of Birth')),
                ('mother_profession', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mother Profession')),
                ('father_name', models.CharField(max_length=30, verbose_name='Father Name')),
                ('father_dob', models.DateField(blank=True, null=True, verbose_name='Father Date of Birth')),
                ('father_profession', models.CharField(blank=True, max_length=50, null=True, verbose_name='Father Profession')),
                ('child1_name', models.CharField(max_length=30, verbose_name='Child1 Name')),
                ('child2_name', models.CharField(max_length=30, verbose_name='Child2 Name')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageProficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_known', models.CharField(blank=True, max_length=50, null=True, verbose_name='Language Known')),
                ('speak', models.CharField(blank=True, max_length=50, null=True, verbose_name='Speak')),
                ('write', models.CharField(blank=True, max_length=50, null=True, verbose_name='Write')),
                ('read', models.CharField(blank=True, max_length=50, null=True, verbose_name='Read')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousEmployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='Company Name')),
                ('company_address', models.CharField(max_length=500, null=True, verbose_name='Company Address')),
                ('employed_from', models.DateField(verbose_name='Start Date')),
                ('employed_upto', models.DateField(verbose_name='End Date')),
                ('last_ctc', models.FloatField(verbose_name='Last CTC')),
                ('reason_for_exit', models.CharField(max_length=200, verbose_name='Reason for Exit')),
                ('job_type', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('CN', 'Contract'), ('IN', 'Intern')], default='PT', max_length=5, verbose_name='Job Type')),
                ('ps_attachment', models.FileField(blank=True, null=True, upload_to=EmployeeForms.models.content_file_name, verbose_name='Pay Slip Attachment')),
                ('rl_attachment', models.FileField(blank=True, null=True, upload_to=EmployeeForms.models.content_file_name, verbose_name='Relieving letter Attachment')),
                ('offer_letter_attachment', models.FileField(blank=True, null=True, upload_to=EmployeeForms.models.content_file_name, verbose_name='Offer letter Attachment')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name='created Date')),
                ('updatedon', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan', models.CharField(max_length=10, verbose_name='PAN Number')),
                ('pan_attachment', models.FileField(blank=True, null=True, upload_to=EmployeeForms.models.content_file_name, verbose_name='Pan Attachment')),
                ('aadhar_card', models.CharField(blank=True, max_length=12, verbose_name='Aadhar Card')),
                ('aadhar_attachment', models.FileField(blank=True, null=True, upload_to=EmployeeForms.models.content_file_name, verbose_name='Aadhar Card Attachment')),
                ('dl', models.CharField(blank=True, max_length=10, null=True, verbose_name='Driving License')),
                ('dl_attachment', models.FileField(blank=True, null=True, upload_to=EmployeeForms.models.content_file_name, verbose_name='DL Attachment')),
                ('passport', models.CharField(blank=True, max_length=10, null=True, verbose_name='Passport')),
                ('passport_attachment', models.FileField(blank=True, null=True, upload_to=EmployeeForms.models.content_file_name, verbose_name='Passport Attachment')),
                ('voter_id', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Voter ID')),
                ('voter_attachment', models.FileField(blank=True, null=True, upload_to=EmployeeForms.models.content_file_name, verbose_name='Voter ID Attachment')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pan', models.CharField(blank=True, max_length=30, null=True, verbose_name='Name(as per PAN)')),
                ('photo', models.FileField(blank=True, null=True, upload_to=EmployeeForms.models.content_file_name, verbose_name='Photo')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2, verbose_name='Gender')),
                ('nationality', models.CharField(max_length=30, verbose_name='Nationality')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, verbose_name='Blood Group')),
                ('mobile_phone', models.CharField(max_length=10, null=True, unique=True, verbose_name='Mobile Phone')),
                ('land_phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Landline Number')),
                ('emergency_phone1', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Emergency Contact Number1')),
                ('emergency_phone2', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Emergency Contact Number2')),
                ('personal_email', models.EmailField(max_length=250, unique=True, verbose_name='Personal E-mail')),
                ('confirmation_code', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Confirmation Code')),
                ('address', models.ManyToManyField(to='EmployeeForms.Address', verbose_name='User Address')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
