# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='aadhar_card',
            field=models.CharField(blank=True, max_length=12, unique=True, verbose_name='Aadhar Card'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='dl',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Driving License'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='passport',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Passport'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='voter_id',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Voter ID'),
        ),
    ]
