# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0003_useraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='employee',
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
