# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0004_auto_20161017_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='address',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='address',
            field=models.ManyToManyField(to='EmployeeForms.Address', verbose_name='User Address'),
        ),
    ]
