# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0005_auto_20161018_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('MA', 'Married'), ('WD', 'Windowed'), ('SE', 'Seperated'), ('DV', 'Divorced'), ('SG', 'Single')], max_length=10, null=True, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='middle_name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Middle Name'),
        ),
    ]
