# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-26 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0007_auto_20161026_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previousemployment',
            name='company_address',
        ),
    ]
