# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-17 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0008_remove_previousemployment_company_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='institution',
            new_name='institute',
        ),
    ]
