# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-18 10:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EmployeeForms', '0009_auto_20161117_0727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_active',
        ),
        migrations.AddField(
            model_name='address',
            name='employee',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='previousemployment',
            name='company_address',
            field=models.CharField(max_length=500, null=True, verbose_name='Company Address'),
        ),
    ]
