# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-22 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0010_auto_20161118_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('PR', 'Permanent'), ('TM', 'Temporary')], default='PR', max_length=2, verbose_name='Address Type'),
        ),
    ]
