# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-22 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0012_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='attachments',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Attachments'),
        ),
    ]
