# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-22 11:31
from __future__ import unicode_literals

import EmployeeForms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0013_auto_20161122_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='attachments',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=EmployeeForms.models.content_file_name, verbose_name='Attachment'),
        ),
    ]
