# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-23 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0014_auto_20161122_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='pan',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='PAN Number'),
        ),
    ]
