# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-23 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0016_auto_20161123_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousemployment',
            name='job_type',
            field=models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('CN', 'Contract'), ('IN', 'Intern')], default='PT', max_length=5, verbose_name='Job Type'),
        ),
    ]
