# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-23 10:55
from __future__ import unicode_literals

import EmployeeForms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0018_remove_previousemployment_pf_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='aadhar_attachment',
            field=models.FileField(blank=True, null=True, upload_to=EmployeeForms.models.content_file_name, verbose_name='Aadhar Card Attachment'),
        ),
        migrations.AddField(
            model_name='proof',
            name='dl_attachment',
            field=models.FileField(blank=True, null=True, upload_to=EmployeeForms.models.content_file_name, verbose_name='DL Attachment'),
        ),
        migrations.AddField(
            model_name='proof',
            name='pan_attachment',
            field=models.FileField(blank=True, null=True, upload_to=EmployeeForms.models.content_file_name, verbose_name='Pan Attachment'),
        ),
        migrations.AddField(
            model_name='proof',
            name='passport_attachment',
            field=models.FileField(blank=True, null=True, upload_to=EmployeeForms.models.content_file_name, verbose_name='Passport Attachment'),
        ),
        migrations.AddField(
            model_name='proof',
            name='voter_attachment',
            field=models.FileField(blank=True, null=True, upload_to=EmployeeForms.models.content_file_name, verbose_name='Voter ID Attachment'),
        ),
    ]
