# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-24 04:42
from __future__ import unicode_literals

import EmployeeForms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0019_auto_20161123_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousemployment',
            name='ps_attachment',
            field=models.FileField(blank=True, null=True, upload_to=EmployeeForms.models.content_file_name, verbose_name='Pay Slip Attachment'),
        ),
        migrations.AddField(
            model_name='previousemployment',
            name='rl_attachment',
            field=models.FileField(blank=True, null=True, upload_to=EmployeeForms.models.content_file_name, verbose_name='Relieving letter Attachment'),
        ),
    ]
