# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-24 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0022_userdetails_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='employee',
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
