# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-24 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0024_auto_20161124_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='aadhar_card',
            field=models.CharField(blank=True, max_length=12, verbose_name='Aadhar Card'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='dl',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Driving License'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='pan',
            field=models.CharField(max_length=10, verbose_name='PAN Number'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='passport',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Passport'),
        ),
    ]
