# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-24 11:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0025_auto_20161124_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
