# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-25 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0027_auto_20161125_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='voter_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Voter ID'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Emergency Contact Number'),
        ),
    ]
