# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-28 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0028_auto_20161125_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='emergency_phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Emergency Contact Number'),
        ),
    ]
