# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-30 11:58
from __future__ import unicode_literals

import EmployeeForms.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EmployeeForms', '0030_auto_20161128_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=EmployeeForms.models.content_file_name, verbose_name='Attachment')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
