# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0031_fileupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='employee',
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
