# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0033_auto_20161202_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='qualification',
            field=models.CharField(choices=[('SSC', 'Senior Secondary'), ('HSC', 'Higher Secondary'), ('GRAD', 'Graduate'), ('PG', 'Post Graduate'), ('PhD', 'Doctrate'), ('Others', 'Others')], max_length=5, unique=True, verbose_name='Qualification'),
        ),
    ]
