# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 04:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0035_auto_20161205_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='date_of_birth',
        ),
    ]
