# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0036_remove_userdetails_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
