# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0037_userdetails_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='emergency_phone',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='emergency_phone1',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Emergency Contact Number1'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='emergency_phone2',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Emergency Contact Number2'),
        ),
    ]
