# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 05:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0038_auto_20161205_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='overall_marks',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Total Score/GPA'),
        ),
    ]
