# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0039_auto_20161205_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='board_university',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Board/University'),
        ),
    ]
