# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-06 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0040_education_board_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='land_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Landline Number'),
        ),
    ]
