# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-07 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0042_auto_20161206_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Confirmation Code'),
        ),
    ]
