# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-07 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0044_confirmationcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmationcode',
            old_name='employee',
            new_name='username',
        ),
    ]
