# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-19 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0045_auto_20161207_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='qualification',
            field=models.CharField(choices=[('SSC', 'Senior Secondary'), ('HSC', 'Higher Secondary'), ('GRAD', 'Graduate'), ('PG', 'Post Graduate'), ('PhD', 'Doctrate'), ('Other', 'Others')], max_length=5, verbose_name='Qualification'),
        ),
        migrations.AlterField(
            model_name='previousemployment',
            name='last_ctc',
            field=models.FloatField(verbose_name='Last CTC'),
        ),
    ]
