# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-21 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0046_auto_20161219_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address1',
            field=models.CharField(max_length=200, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(max_length=200, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('MA', 'Married'), ('SG', 'Single'), ('SE', 'Seperated'), ('DV', 'Divorced'), ('WD', 'Windowed')], max_length=10, null=True, verbose_name='Marital Status'),
        ),
    ]
