# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-27 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0047_auto_20161221_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='emergency_phone1',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Emergency Contact Number1'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='emergency_phone2',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Emergency Contact Number2'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='land_phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Landline Number'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='mobile_phone',
            field=models.IntegerField(unique=True, verbose_name='Mobile Phone'),
        ),
    ]
