# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-27 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0048_auto_20161227_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='mobile_phone',
            field=models.FloatField(max_length=10, unique=True, verbose_name='Mobile Phone'),
        ),
    ]
