# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-27 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0049_auto_20161227_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='emergency_phone1',
            field=models.FloatField(blank=True, max_length=10, null=True, unique=True, verbose_name='Emergency Contact Number1'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='emergency_phone2',
            field=models.FloatField(blank=True, max_length=10, null=True, unique=True, verbose_name='Emergency Contact Number2'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='land_phone',
            field=models.FloatField(blank=True, max_length=10, null=True, verbose_name='Landline Number'),
        ),
    ]
