# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0052_auto_20161228_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='first_name_pan',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='First Name(as per PAN)'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='last_name_pan',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Last Name(as per PAN)'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='middle_name_pan',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Middle Name(as per PAN)'),
        ),
        migrations.AlterField(
            model_name='previousemployment',
            name='reason_for_exit',
            field=models.CharField(max_length=100, verbose_name='Reason for Exit'),
        ),
    ]
