# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0053_auto_20170102_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='education_type',
            field=models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('DS', 'Distance Education')], default='FT', max_length=5, verbose_name='Education Type'),
        ),
    ]
