# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 05:57
from __future__ import unicode_literals

import EmployeeForms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0054_education_education_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousemployment',
            name='offer_letter_attachment',
            field=models.FileField(blank=True, null=True, upload_to=EmployeeForms.models.content_file_name, verbose_name='Offer letter Attachment'),
        ),
    ]
