# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0055_previousemployment_offer_letter_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='first_name_pan',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='last_name_pan',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='middle_name_pan',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='name_pan',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Name(as per PAN)'),
        ),
    ]
