# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 08:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EmployeeForms', '0056_auto_20170103_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(blank=True, choices=[('MA', 'Married'), ('SG', 'Single'), ('SE', 'Seperated'), ('DV', 'Divorced'), ('WD', 'Windowed')], max_length=10, null=True, verbose_name='Marital Status')),
                ('wedding_date', models.DateField(blank=True, null=True, verbose_name='Wedding Date')),
                ('spouse_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Spouse Name')),
                ('no_of_children', models.CharField(blank=True, max_length=10, null=True, verbose_name='Number of Children')),
                ('mother_name', models.CharField(max_length=30, verbose_name='Mother Name')),
                ('mother_dob', models.DateField(blank=True, null=True, verbose_name='Mother Date of Birth')),
                ('mother_profession', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mother Profession')),
                ('father_name', models.CharField(max_length=30, verbose_name='Father Name')),
                ('father_dob', models.DateField(blank=True, null=True, verbose_name='Father Date of Birth')),
                ('father_profession', models.CharField(blank=True, max_length=50, null=True, verbose_name='Father Profession')),
                ('child1_name', models.CharField(max_length=30, verbose_name='Child1 Name')),
                ('child2_name', models.CharField(max_length=30, verbose_name='Child2 Name')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='wedding_date',
        ),
    ]
