# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 10:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EmployeeForms', '0057_auto_20170103_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageProficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_known', models.CharField(blank=True, max_length=50, null=True, verbose_name='Language Known')),
                ('speak', models.CharField(blank=True, max_length=50, null=True, verbose_name='Speak')),
                ('write', models.CharField(blank=True, max_length=50, null=True, verbose_name='Write')),
                ('read', models.CharField(blank=True, max_length=50, null=True, verbose_name='Read')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
