# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0058_languageproficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('PR', 'Permanent'), ('TM', 'Temporary')], default='TM', max_length=2, verbose_name='Address Type'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='name_pan',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Name(as per PAN)'),
        ),
    ]
