# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-04 05:38
from __future__ import unicode_literals

import EmployeeForms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForms', '0059_auto_20170103_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=EmployeeForms.models.content_file_name, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('PR', 'Permanent'), ('TM', 'Temporary')], default='PR', max_length=2, verbose_name='Address Type'),
        ),
    ]
